// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGUn9adhMox2HKOyGM-m6LBaq_fNnVmus',
    appId: '1:372935907369:web:7333a7c783bb7eda9d6438',
    messagingSenderId: '372935907369',
    projectId: 'courses-c6881',
    authDomain: 'courses-c6881.firebaseapp.com',
    databaseURL: 'https://courses-c6881-default-rtdb.firebaseio.com',
    storageBucket: 'courses-c6881.appspot.com',
    measurementId: 'G-R2GDEP90PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwAUVFHeujSB5n15hzsAJWcwFjjJcv9zY',
    appId: '1:372935907369:android:a34060d723e572879d6438',
    messagingSenderId: '372935907369',
    projectId: 'courses-c6881',
    databaseURL: 'https://courses-c6881-default-rtdb.firebaseio.com',
    storageBucket: 'courses-c6881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFvn_NKoJEV7u8V77Y8rPi40i0nLD3g8',
    appId: '1:372935907369:ios:2f1302d59a8754b79d6438',
    messagingSenderId: '372935907369',
    projectId: 'courses-c6881',
    databaseURL: 'https://courses-c6881-default-rtdb.firebaseio.com',
    storageBucket: 'courses-c6881.appspot.com',
    iosBundleId: 'com.example.dars47',
  );
}
